// Code generated by calque. DO NOT EDIT.

import type { Client as C } from "@connectrpc/connect";
import type { QueryDescOf } from "@heojeongbo/calque-dexie";

import { ItemService } from "./item_svc.g_pb";

export type ItemServiceClient = C<typeof ItemService>

export interface ServiceClient {
	readonly item: ItemServiceClient;
}

export const item= ItemService.method;

export const queries = {
	["example.v1.ItemService"]: {
		pick: v => ({key:{case: "id", value: v.id}}),
		refs: v => [
			{key:{case: "id", value: v.id}},
			{key:{case: "name", value: v.name}},
		],
		rpc: {
			add: {
				desc: item.add,
				extract: v => v
			},
			get: {
				desc: item.get,
				extract: v => v
			},
			patch: {
				desc: item.patch,
				extract: v => v
			},
			erase: {
				desc: item.erase,
				extract: v => undefined
			},
			list: {
				desc: item.list,
				extract: v => v.items
			},
		}
	} satisfies QueryDescOf<typeof ItemService>,
}

