// Code generated by calque. DO NOT EDIT.

import * as Item from "./item.db.g";

export type Db = 
	& Item.Db

export interface DbClient {
	readonly item: Item.TableService
}

export const DbService = {
	[Item.TableName]: Item.TableService,
}

export function schemas(){
	return {
		[Item.TableName]: Item.Schema,
	} as const
}
