// Code generated by calque. DO NOT EDIT.

import { create, isFieldSet, type MessageInitShape } from "@bufbuild/protobuf";
import { type Empty, EmptySchema } from "@bufbuild/protobuf/wkt";
import { Code } from "@connectrpc/connect";
import type { DbOf, EntityOf, Key, ValueOf } from "@heojeongbo/calque-dexie";
import { TableBase, uuid } from "@heojeongbo/calque-dexie";

import type { ItemServiceClient } from "./client.g"
import { type Item, ItemSchema } from "./item_pb"
import { ItemAddRequestSchema, ItemGetRequestSchema, ItemPatchRequestSchema, ItemRefSchema } from "./item_svc.g_pb"

type Desc = typeof ItemSchema
export type Db = DbOf<Desc>

export const TableName = "example.v1.Item";
export const Schema = "&id,&name" as const;

export class TableService extends TableBase<Desc> implements Partial<ItemServiceClient> {
	constructor(db: Db) {
		super(db, ItemSchema);
	}

	_dehydrate(v: Item): [Key, any] {
		const w = v as unknown as any
		const k = uuid.u8_str(v.id)
		if(k === undefined) throw this._err("invalid key", Code.InvalidArgument)
		w.id = k
		return [k, v]
	}

	_hydrate(v: any): Item {
		v.id = uuid.str_u8(v.id)
		return create(this._schema, v)
	}

	get(req: MessageInitShape<typeof ItemGetRequestSchema>): Promise<Item> {
		if(req.ref?.key === undefined) return Promise.reject(this._err("key undefined", Code.InvalidArgument));
		const { key } = req.ref;
		switch(key.case) {
			case "id": {
				const k = uuid.u8_str(key.value);
				if(k === undefined) return Promise.reject(this._err("invalid key", Code.InvalidArgument));
				return this._query(t => t.get(k));
			}

			case "name": {
				const k = key.value
				const q = { name: k }
				return this._query(t => t.where(q).first());
			}

			default:
				return Promise.reject(this._err(`unknown key: ${key.case}`, Code.InvalidArgument));
		}
	}

	_by(key: NonNullable<MessageInitShape<typeof ItemRefSchema>["key"]>): Key | { [k: string]: unknown } {
		switch(key.case) {
			case "id": {
				const k = uuid.u8_str(key.value);
				if(k === undefined) throw this._err("invalid key", Code.InvalidArgument);
				return k;
			}
			case "name": {
				return { 'name': key.value };
			}
			default:
				throw this._err(`unknown key: ${key.case}`, Code.InvalidArgument);
		}
	}

	async add(req: MessageInitShape<typeof ItemAddRequestSchema>): Promise<Item> {
		req = create(ItemAddRequestSchema, req);
		const w: { [k: string]: unknown } = {};
		w.id = isFieldSet(req, ItemAddRequestSchema.field.id) ? req.id : uuid.str_u8(crypto.randomUUID());
		if(isFieldSet(req, ItemAddRequestSchema.field.name)) w.name = req.name;
		if(isFieldSet(req, ItemAddRequestSchema.field.description)) w.description = req.description;
		const v = create(ItemSchema, w as MessageInitShape<Desc>);
		await this._insert(v);
		return v;
	}

	async patch(req: MessageInitShape<typeof ItemPatchRequestSchema>): Promise<Item> {
		req = create(ItemPatchRequestSchema, req);
		const key = req.ref?.key;
		if(key === undefined) throw this._err("key undefined", Code.InvalidArgument);
		return this._update(this._by(key), u => {
			const w = { ...u } as { [k: string]: unknown };
			delete w.$typeName;
			delete w.$unknown;
			if(isFieldSet(req, ItemPatchRequestSchema.field.name)) w.name = req.name;
			if(isFieldSet(req, ItemPatchRequestSchema.field.description)) w.description = req.description;
			return create(ItemSchema, w as MessageInitShape<Desc>);
		});
	}

	async erase(req: MessageInitShape<typeof ItemRefSchema>): Promise<Empty> {
		req = create(ItemRefSchema, req);
		const key = req.key;
		if(key === undefined) throw this._err("key undefined", Code.InvalidArgument);
		await this._delete(this._by(key));
		return create(EmptySchema);
	}
}
