// Code generated by calque. DO NOT EDIT.
// source: example/v1/item.proto

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file example/v1/item_svc.g.proto (package example.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Item, ItemSchema } from "./item_pb";
import { file_example_v1_item } from "./item_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file example/v1/item_svc.g.proto.
 */
export const file_example_v1_item_svc_g: GenFile = /*@__PURE__*/
  fileDesc("ChtleGFtcGxlL3YxL2l0ZW1fc3ZjLmcucHJvdG8SCmV4YW1wbGUudjEiPwoOSXRlbUFkZFJlcXVlc3QSCgoCaWQYASABKAwSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCSIuCgdJdGVtUmVmEgwKAmlkGAEgASgMSAASDgoEbmFtZRgCIAEoCUgAQgUKA2tleSI8CgpJdGVtU2VsZWN0EgsKA2FsbBgBIAEoCBIMCgRuYW1lGAIgASgIEhMKC2Rlc2NyaXB0aW9uGAMgASgIIloKDkl0ZW1HZXRSZXF1ZXN0EiAKA3JlZhgBIAEoCzITLmV4YW1wbGUudjEuSXRlbVJlZhImCgZzZWxlY3QYAiABKAsyFi5leGFtcGxlLnYxLkl0ZW1TZWxlY3QiVwoQSXRlbVBhdGNoUmVxdWVzdBIgCgNyZWYYASABKAsyEy5leGFtcGxlLnYxLkl0ZW1SZWYSDAoEbmFtZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgFIAEoCSI4CgpJdGVtRmlsdGVyEiIKA3JlZhgBIAEoCzITLmV4YW1wbGUudjEuSXRlbVJlZkgAQgYKBGtpbmQihAEKD0l0ZW1MaXN0UmVxdWVzdBInCgdmaWx0ZXJzGAEgAygLMhYuZXhhbXBsZS52MS5JdGVtRmlsdGVyEiYKBnNlbGVjdBgCIAEoCzIWLmV4YW1wbGUudjEuSXRlbVNlbGVjdBIUCgVsaW1pdBgFIAEoBEIFqgECCAJKBAgDEARKBAgEEAUiMwoQSXRlbUxpc3RSZXNwb25zZRIfCgVpdGVtcxgBIAMoCzIQLmV4YW1wbGUudjEuSXRlbTKpAgoLSXRlbVNlcnZpY2USMwoDQWRkEhouZXhhbXBsZS52MS5JdGVtQWRkUmVxdWVzdBoQLmV4YW1wbGUudjEuSXRlbRIzCgNHZXQSGi5leGFtcGxlLnYxLkl0ZW1HZXRSZXF1ZXN0GhAuZXhhbXBsZS52MS5JdGVtEjcKBVBhdGNoEhwuZXhhbXBsZS52MS5JdGVtUGF0Y2hSZXF1ZXN0GhAuZXhhbXBsZS52MS5JdGVtEjQKBUVyYXNlEhMuZXhhbXBsZS52MS5JdGVtUmVmGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkEKBExpc3QSGy5leGFtcGxlLnYxLkl0ZW1MaXN0UmVxdWVzdBocLmV4YW1wbGUudjEuSXRlbUxpc3RSZXNwb25zZUIiWiBleGFtcGxlLmNvbS9leGFtcGxlL3YxO2V4YW1wbGV2MWIIZWRpdGlvbnNw6Ac", [file_example_v1_item, file_google_protobuf_empty]);

/**
 * @generated from message example.v1.ItemAddRequest
 */
export type ItemAddRequest = Message<"example.v1.ItemAddRequest"> & {
  /**
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message example.v1.ItemAddRequest.
 * Use `create(ItemAddRequestSchema)` to create a new message.
 */
export const ItemAddRequestSchema: GenMessage<ItemAddRequest> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 0);

/**
 * @generated from message example.v1.ItemRef
 */
export type ItemRef = Message<"example.v1.ItemRef"> & {
  /**
   * @generated from oneof example.v1.ItemRef.key
   */
  key: {
    /**
     * @generated from field: bytes id = 1;
     */
    value: Uint8Array;
    case: "id";
  } | {
    /**
     * @generated from field: string name = 2;
     */
    value: string;
    case: "name";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message example.v1.ItemRef.
 * Use `create(ItemRefSchema)` to create a new message.
 */
export const ItemRefSchema: GenMessage<ItemRef> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 1);

/**
 * @generated from message example.v1.ItemSelect
 */
export type ItemSelect = Message<"example.v1.ItemSelect"> & {
  /**
   * @generated from field: bool all = 1;
   */
  all: boolean;

  /**
   * @generated from field: bool name = 2;
   */
  name: boolean;

  /**
   * @generated from field: bool description = 3;
   */
  description: boolean;
};

/**
 * Describes the message example.v1.ItemSelect.
 * Use `create(ItemSelectSchema)` to create a new message.
 */
export const ItemSelectSchema: GenMessage<ItemSelect> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 2);

/**
 * @generated from message example.v1.ItemGetRequest
 */
export type ItemGetRequest = Message<"example.v1.ItemGetRequest"> & {
  /**
   * @generated from field: example.v1.ItemRef ref = 1;
   */
  ref?: ItemRef | undefined;

  /**
   * @generated from field: example.v1.ItemSelect select = 2;
   */
  select?: ItemSelect | undefined;
};

/**
 * Describes the message example.v1.ItemGetRequest.
 * Use `create(ItemGetRequestSchema)` to create a new message.
 */
export const ItemGetRequestSchema: GenMessage<ItemGetRequest> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 3);

/**
 * @generated from message example.v1.ItemPatchRequest
 */
export type ItemPatchRequest = Message<"example.v1.ItemPatchRequest"> & {
  /**
   * @generated from field: example.v1.ItemRef ref = 1;
   */
  ref?: ItemRef | undefined;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;
};

/**
 * Describes the message example.v1.ItemPatchRequest.
 * Use `create(ItemPatchRequestSchema)` to create a new message.
 */
export const ItemPatchRequestSchema: GenMessage<ItemPatchRequest> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 4);

/**
 * @generated from message example.v1.ItemFilter
 */
export type ItemFilter = Message<"example.v1.ItemFilter"> & {
  /**
   * @generated from oneof example.v1.ItemFilter.kind
   */
  kind: {
    /**
     * @generated from field: example.v1.ItemRef ref = 1;
     */
    value: ItemRef;
    case: "ref";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message example.v1.ItemFilter.
 * Use `create(ItemFilterSchema)` to create a new message.
 */
export const ItemFilterSchema: GenMessage<ItemFilter> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 5);

/**
 * @generated from message example.v1.ItemListRequest
 */
export type ItemListRequest = Message<"example.v1.ItemListRequest"> & {
  /**
   * @generated from field: repeated example.v1.ItemFilter filters = 1;
   */
  filters: ItemFilter[];

  /**
   * @generated from field: example.v1.ItemSelect select = 2;
   */
  select?: ItemSelect | undefined;

  /**
   * @generated from field: uint64 limit = 5 [features.field_presence = IMPLICIT];
   */
  limit: bigint;
};

/**
 * Describes the message example.v1.ItemListRequest.
 * Use `create(ItemListRequestSchema)` to create a new message.
 */
export const ItemListRequestSchema: GenMessage<ItemListRequest> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 6);

/**
 * @generated from message example.v1.ItemListResponse
 */
export type ItemListResponse = Message<"example.v1.ItemListResponse"> & {
  /**
   * @generated from field: repeated example.v1.Item items = 1;
   */
  items: Item[];
};

/**
 * Describes the message example.v1.ItemListResponse.
 * Use `create(ItemListResponseSchema)` to create a new message.
 */
export const ItemListResponseSchema: GenMessage<ItemListResponse> = /*@__PURE__*/
  messageDesc(file_example_v1_item_svc_g, 7);

/**
 * @generated from service example.v1.ItemService
 */
export const ItemService: GenService<{
  /**
   * Add creates a new Item
   *
   * @generated from rpc example.v1.ItemService.Add
   */
  add: {
    methodKind: "unary";
    input: typeof ItemAddRequestSchema;
    output: typeof ItemSchema;
  },
  /**
   * Get retrieves an Item
   *
   * @generated from rpc example.v1.ItemService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof ItemGetRequestSchema;
    output: typeof ItemSchema;
  },
  /**
   * Patch updates an existing Item
   *
   * @generated from rpc example.v1.ItemService.Patch
   */
  patch: {
    methodKind: "unary";
    input: typeof ItemPatchRequestSchema;
    output: typeof ItemSchema;
  },
  /**
   * Erase deletes an Item
   *
   * @generated from rpc example.v1.ItemService.Erase
   */
  erase: {
    methodKind: "unary";
    input: typeof ItemRefSchema;
    output: typeof EmptySchema;
  },
  /**
   * List reads the Items the filters match
   *
   * @generated from rpc example.v1.ItemService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ItemListRequestSchema;
    output: typeof ItemListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_example_v1_item_svc_g, 0);

