// The Tier 2 schema: the same Item, annotated so calque can generate an
// offline store for it.
//
// Kept separate from `proto/example/v1/item.proto` on purpose. That one is the
// default path and stays free of ORM vocabulary; this whole directory is
// opt-in and deletable. See ../../../../README.md.
//
// `edition = "2023"` and not `proto3`: the orm vocabulary is edition-2023, and
// an importer has to be at least as new as what it imports.

// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file example/v1/item.proto (package example.v1, edition 2023)
// option features.field_presence = IMPLICIT;
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_orm } from "../../orm_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file example/v1/item.proto.
 */
export const file_example_v1_item: GenFile = /*@__PURE__*/
  fileDesc("ChVleGFtcGxlL3YxL2l0ZW0ucHJvdG8SCmV4YW1wbGUudjEiYwoESXRlbRIXCgJpZBgBIAEoDEIL6oIWBxBAKAGCAQASFwoEbmFtZRgCIAEoCUIJ6oIWBTABggEAEhwKC2Rlc2NyaXB0aW9uGAMgASgJQgfqghYDggEAOgvK/BUHEgUQAaIBAEInWiBleGFtcGxlLmNvbS9leGFtcGxlL3YxO2V4YW1wbGV2MZIDAggCYghlZGl0aW9uc3DoBw", [file_orm]);

/**
 * @generated from message example.v1.Item
 */
export type Item = Message<"example.v1.Item"> & {
  /**
   * `TYPE_UUID` over a string id: calque stores it as 16 bytes and hands the
   * TS side a hyphenated string, so the index is compact without the app ever
   * seeing the byte form.
   *
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array;

  /**
   * `unique` becomes a real uniqueness constraint in the generated store, not
   * a comment — a duplicate insert fails locally rather than at the server.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message example.v1.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/
  messageDesc(file_example_v1_item, 0);

