/**
 * Regenerates `src/ui/index.ts` from the component folders next to it.
 *
 * The barrel is derived, not hand-maintained: `pnpm ui:add` scaffolds a new
 * folder and knows nothing about our public API, so re-deriving is the only way
 * the barrel cannot drift from what is on disk. Idempotent.
 *
 * `primitive/` is excluded on purpose — it is the shadcn CLI's territory and is
 * not part of the public surface. Anything there reaches consumers only through
 * the `ui/<name>/` wrapper that re-exports it.
 *
 * The barrel is a convenience for app code. Anything performance-sensitive
 * should deep-import (`@template/design/ui/button`) so a single component does
 * not pull the whole graph into a route chunk.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const uiDir = path.resolve(dirname, "../src/ui");
const barrel = path.join(uiDir, "index.ts");

const PRIVATE_DIRS = new Set(["primitive"]);

fs.mkdirSync(uiDir, { recursive: true });

const modules = fs
	.readdirSync(uiDir, { withFileTypes: true })
	.filter((entry) => entry.isDirectory() && !PRIVATE_DIRS.has(entry.name))
	.map((entry) => entry.name)
	.filter((name) => fs.existsSync(path.join(uiDir, name, "index.ts")))
	.sort();

const body = [
	"// GENERATED by `pnpm ui:sync` — do not edit by hand.",
	...modules.map((m) => `export * from "./${m}";`),
	"",
].join("\n");

const prev = fs.existsSync(barrel) ? fs.readFileSync(barrel, "utf8") : "";
if (prev === body) {
	console.log(`ui barrel already current (${modules.length} components)`);
} else {
	fs.writeFileSync(barrel, body);
	console.log(`ui barrel written (${modules.length} components)`);
}
