/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as publicSigninRouteImport } from './routes/(public)/signin'
import { Route as authshellRouteRouteImport } from './routes/(auth)/(shell)/route'
import { Route as authshellIndexRouteImport } from './routes/(auth)/(shell)/index'
import { Route as authshellItemsIndexRouteImport } from './routes/(auth)/(shell)/items/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSigninRoute = publicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => publicRouteRoute,
} as any)
const authshellRouteRoute = authshellRouteRouteImport.update({
  id: '/(shell)',
  getParentRoute: () => authRouteRoute,
} as any)
const authshellIndexRoute = authshellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authshellRouteRoute,
} as any)
const authshellItemsIndexRoute = authshellItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => authshellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/signin': typeof publicSigninRoute
  '/': typeof authshellIndexRoute
  '/items/': typeof authshellItemsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/signin': typeof publicSigninRoute
  '/': typeof authshellIndexRoute
  '/items': typeof authshellItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(auth)/(shell)': typeof authshellRouteRouteWithChildren
  '/(public)/signin': typeof publicSigninRoute
  '/(auth)/(shell)/': typeof authshellIndexRoute
  '/(auth)/(shell)/items/': typeof authshellItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/signin' | '/' | '/items/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/signin' | '/' | '/items'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/$'
    | '/(auth)/(shell)'
    | '/(public)/signin'
    | '/(auth)/(shell)/'
    | '/(auth)/(shell)/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signin': {
      id: '/(public)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicSigninRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/(shell)': {
      id: '/(auth)/(shell)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authshellRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(shell)/': {
      id: '/(auth)/(shell)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authshellIndexRouteImport
      parentRoute: typeof authshellRouteRoute
    }
    '/(auth)/(shell)/items/': {
      id: '/(auth)/(shell)/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof authshellItemsIndexRouteImport
      parentRoute: typeof authshellRouteRoute
    }
  }
}

interface authshellRouteRouteChildren {
  authshellIndexRoute: typeof authshellIndexRoute
  authshellItemsIndexRoute: typeof authshellItemsIndexRoute
}

const authshellRouteRouteChildren: authshellRouteRouteChildren = {
  authshellIndexRoute: authshellIndexRoute,
  authshellItemsIndexRoute: authshellItemsIndexRoute,
}

const authshellRouteRouteWithChildren = authshellRouteRoute._addFileChildren(
  authshellRouteRouteChildren,
)

interface authRouteRouteChildren {
  authshellRouteRoute: typeof authshellRouteRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authshellRouteRoute: authshellRouteRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicSigninRoute: typeof publicSigninRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicSigninRoute: publicSigninRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
