#!/usr/bin/env node
/**
 * `pnpm rename:scope @acme [app-name]` — rebrand the template in one command.
 *
 * The template ships as `@template/{web,design,core,interfaces}`. That scope
 * appears in package names, `exports` maps, tsconfig `paths`, Vite aliases,
 * `components.json`, every import, and the docs — eight places that must agree
 * or the build fails in the confusing way (resolves in Vite, not in tsc). This
 * script is what keeps "fork the template" from starting with a find-replace
 * the user gets 90% right.
 *
 * It rewrites a literal string, deliberately: a regex over import statements
 * would miss the JSON and Markdown occurrences, which are exactly the ones a
 * manual rename forgets.
 *
 *   node scripts/rename-scope.mjs @acme            # scope only
 *   node scripts/rename-scope.mjs @acme my-app     # scope + root package name
 *   node scripts/rename-scope.mjs @acme --dry      # show the diff, change nothing
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OLD_SCOPE = "@template";
const OLD_ROOT_NAME = "ui-app-template";

const SKIP_DIRS = new Set([
	"node_modules",
	".git",
	"dist",
	"build",
	"coverage",
	".intlayer",
	".tanstack",
	"test-results",
	"playwright-report",
]);

// The lockfile is regenerated by `pnpm install`; rewriting it by hand produces
// an integrity mismatch rather than a working install.
const SKIP_FILES = new Set(["pnpm-lock.yaml", "rename-scope.mjs"]);

const TEXT_EXTS = new Set([
	".ts",
	".tsx",
	".mts",
	".js",
	".jsx",
	".mjs",
	".json",
	".jsonc",
	".md",
	".css",
	".html",
	".yaml",
	".yml",
	".proto",
]);

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);

function parseArgs(argv) {
	const positional = argv.filter((a) => !a.startsWith("--"));
	const dry = argv.includes("--dry");
	const [scope, rootName] = positional;

	if (!scope) {
		console.error(
			"usage: node scripts/rename-scope.mjs <@scope> [root-package-name] [--dry]",
		);
		process.exit(1);
	}
	if (!/^@[a-z0-9][a-z0-9._-]*$/.test(scope)) {
		console.error(
			`invalid scope: ${scope}\nA scope is "@" followed by lowercase letters, digits, "-", "_" or "." (npm's rule).`,
		);
		process.exit(1);
	}
	if (scope === OLD_SCOPE) {
		console.error(`scope is already ${OLD_SCOPE} — nothing to do.`);
		process.exit(1);
	}
	if (rootName && !/^[a-z0-9][a-z0-9._-]*$/.test(rootName)) {
		console.error(`invalid package name: ${rootName}`);
		process.exit(1);
	}
	return { scope, rootName, dry };
}

function* walk(dir) {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (entry.isDirectory()) {
			if (SKIP_DIRS.has(entry.name)) continue;
			yield* walk(path.join(dir, entry.name));
		} else if (entry.isFile()) {
			if (SKIP_FILES.has(entry.name)) continue;
			if (!TEXT_EXTS.has(path.extname(entry.name))) continue;
			yield path.join(dir, entry.name);
		}
	}
}

function countOccurrences(haystack, needle) {
	return haystack.split(needle).length - 1;
}

const { scope, rootName, dry } = parseArgs(process.argv.slice(2));

let filesChanged = 0;
let replacements = 0;

for (const file of walk(repoRoot)) {
	const before = fs.readFileSync(file, "utf8");
	let after = before;

	const scopeHits = countOccurrences(after, `${OLD_SCOPE}/`);
	if (scopeHits > 0) after = after.split(`${OLD_SCOPE}/`).join(`${scope}/`);

	let nameHits = 0;
	if (rootName) {
		nameHits = countOccurrences(after, OLD_ROOT_NAME);
		if (nameHits > 0) after = after.split(OLD_ROOT_NAME).join(rootName);
	}

	const hits = scopeHits + nameHits;
	if (hits === 0) continue;

	filesChanged += 1;
	replacements += hits;
	console.log(
		`${dry ? "would update" : "updated"} ${path.relative(repoRoot, file)} (${hits})`,
	);
	if (!dry) fs.writeFileSync(file, after);
}

console.log(
	`\n${dry ? "dry run: " : ""}${replacements} replacement(s) across ${filesChanged} file(s)`,
);

if (!dry && filesChanged > 0) {
	console.log(
		"\nNext: `pnpm install` to relink the workspace, then `pnpm type:check`.",
	);
}
