// Code generated by calque. DO NOT EDIT.

import type { Client as C } from "@connectrpc/connect";
import type { QueryDescOf } from "@heojeongbo/calque-dexie";



export interface ServiceClient {
}


export const queries = {
}

