// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file orm/options.proto (package orm, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Index } from "./index_pb";
import { file_orm_index } from "./index_pb";
import type { Ref } from "./ref_pb";
import { file_orm_ref } from "./ref_pb";
import type { RpcAdd, RpcErase, RpcGet, RpcList, RpcPatch } from "./rpc_pb";
import { file_orm_rpc } from "./rpc_pb";
import type { Scope } from "./scope_pb";
import { file_orm_scope } from "./scope_pb";
import type { Type } from "./type_pb";
import { file_orm_type } from "./type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orm/options.proto.
 */
export const file_orm_options: GenFile = /*@__PURE__*/
  fileDesc("ChFvcm0vb3B0aW9ucy5wcm90bxIDb3JtIrgBCgpScGNPcHRpb25zEhAKCGRpc2FibGVkGAEgASgIEgwKBGNydWQYAiABKAgSGAoDYWRkGBAgASgLMgsub3JtLlJwY0FkZBIYCgNnZXQYESABKAsyCy5vcm0uUnBjR2V0EhwKBXBhdGNoGBIgASgLMg0ub3JtLlJwY1BhdGNoEhwKBWVyYXNlGBMgASgLMg0ub3JtLlJwY0VyYXNlEhoKBGxpc3QYFCABKAsyDC5vcm0uUnBjTGlzdCJ4Cg5NZXNzYWdlT3B0aW9ucxIQCghkaXNhYmxlZBgBIAEoCBIcCgNycGMYAiABKAsyDy5vcm0uUnBjT3B0aW9ucxIbCgdpbmRleGVzGAMgAygLMgoub3JtLkluZGV4EhkKBXNjb3BlGBQgASgLMgoub3JtLlNjb3BlItYBCgxGaWVsZE9wdGlvbnMSEAoIZGlzYWJsZWQYASABKAgSFwoEdHlwZRgCIAEoDjIJLm9ybS5UeXBlEgsKA2tleRgFIAEoCBIOCgZ1bmlxdWUYBiABKAgSEAoIbnVsbGFibGUYByABKAgSEQoJaW1tdXRhYmxlGAggASgIEg8KB2RlZmF1bHQYECABKAkSJAoHdmVyc2lvbhgRIAEoCzITLm9ybS5WZXJzaW9uT3B0aW9ucxIiCgZlcmFzZWQYEiABKAsyEi5vcm0uRXJhc2VkT3B0aW9ucyKVAQoLRWRnZU9wdGlvbnMSEAoIZGlzYWJsZWQYASABKAgSFgoEYmluZBgCIAEoCzIILm9ybS5SZWYSFgoEZnJvbRgDIAEoCzIILm9ybS5SZWYSDgoGdW5pcXVlGAYgASgIEhAKCG51bGxhYmxlGAcgASgIEhEKCWltbXV0YWJsZRgIIAEoCBIPCgdkZWZhdWx0GBAgASgJIhAKDlZlcnNpb25PcHRpb25zIg8KDUVyYXNlZE9wdGlvbnNCLFoqZ2l0aHViLmNvbS9wcm90b2J1Zi1vcm0vcHJvdG9idWYtb3JtL29ybXBiYghlZGl0aW9uc3DoBw", [file_orm_index, file_orm_ref, file_orm_rpc, file_orm_scope, file_orm_type]);

/**
 * @generated from message orm.RpcOptions
 */
export type RpcOptions = Message<"orm.RpcOptions"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;

  /**
   * Enables add, get, patch, and erase.
   *
   * @generated from field: bool crud = 2;
   */
  crud: boolean;

  /**
   * @generated from field: orm.RpcAdd add = 16;
   */
  add?: RpcAdd | undefined;

  /**
   * @generated from field: orm.RpcGet get = 17;
   */
  get?: RpcGet | undefined;

  /**
   * @generated from field: orm.RpcPatch patch = 18;
   */
  patch?: RpcPatch | undefined;

  /**
   * @generated from field: orm.RpcErase erase = 19;
   */
  erase?: RpcErase | undefined;

  /**
   * 20 is calque's, not upstream's; the drift tests hold this number against
   * a future upstream release claiming it.
   *
   * @generated from field: orm.RpcList list = 20;
   */
  list?: RpcList | undefined;
};

/**
 * Describes the message orm.RpcOptions.
 * Use `create(RpcOptionsSchema)` to create a new message.
 */
export const RpcOptionsSchema: GenMessage<RpcOptions> = /*@__PURE__*/
  messageDesc(file_orm_options, 0);

/**
 * @generated from message orm.MessageOptions
 */
export type MessageOptions = Message<"orm.MessageOptions"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;

  /**
   * @generated from field: orm.RpcOptions rpc = 2;
   */
  rpc?: RpcOptions | undefined;

  /**
   * @generated from field: repeated orm.Index indexes = 3;
   */
  indexes: Index[];

  /**
   * 20 is calque's, not upstream's, on the same terms as RpcOptions.list: the
   * drift tests hold the number against a future upstream release claiming
   * it. It sits beside `rpc` rather than under it because it is not about
   * which operations exist -- it is about what this entity answers to, which
   * every read has to honour whether or not the operation was generated.
   *
   * @generated from field: orm.Scope scope = 20;
   */
  scope?: Scope | undefined;
};

/**
 * Describes the message orm.MessageOptions.
 * Use `create(MessageOptionsSchema)` to create a new message.
 */
export const MessageOptionsSchema: GenMessage<MessageOptions> = /*@__PURE__*/
  messageDesc(file_orm_options, 1);

/**
 * @generated from message orm.FieldOptions
 */
export type FieldOptions = Message<"orm.FieldOptions"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;

  /**
   * @generated from field: orm.Type type = 2;
   */
  type: Type;

  /**
   * @generated from field: bool key = 5;
   */
  key: boolean;

  /**
   * @generated from field: bool unique = 6;
   */
  unique: boolean;

  /**
   * @generated from field: bool nullable = 7;
   */
  nullable: boolean;

  /**
   * @generated from field: bool immutable = 8;
   */
  immutable: boolean;

  /**
   * TODO: Any?
   *
   * @generated from field: string default = 16;
   */
  default: string;

  /**
   * @generated from field: orm.VersionOptions version = 17;
   */
  version?: VersionOptions | undefined;

  /**
   * @generated from field: orm.ErasedOptions erased = 18;
   */
  erased?: ErasedOptions | undefined;
};

/**
 * Describes the message orm.FieldOptions.
 * Use `create(FieldOptionsSchema)` to create a new message.
 */
export const FieldOptionsSchema: GenMessage<FieldOptions> = /*@__PURE__*/
  messageDesc(file_orm_options, 2);

/**
 * @generated from message orm.EdgeOptions
 */
export type EdgeOptions = Message<"orm.EdgeOptions"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;

  /**
   * @generated from field: orm.Ref bind = 2;
   */
  bind?: Ref | undefined;

  /**
   * @generated from field: orm.Ref from = 3;
   */
  from?: Ref | undefined;

  /**
   * @generated from field: bool unique = 6;
   */
  unique: boolean;

  /**
   * @generated from field: bool nullable = 7;
   */
  nullable: boolean;

  /**
   * @generated from field: bool immutable = 8;
   */
  immutable: boolean;

  /**
   * TODO: Any?
   *
   * @generated from field: string default = 16;
   */
  default: string;
};

/**
 * Describes the message orm.EdgeOptions.
 * Use `create(EdgeOptionsSchema)` to create a new message.
 */
export const EdgeOptionsSchema: GenMessage<EdgeOptions> = /*@__PURE__*/
  messageDesc(file_orm_options, 3);

/**
 * @generated from message orm.VersionOptions
 */
export type VersionOptions = Message<"orm.VersionOptions"> & {
};

/**
 * Describes the message orm.VersionOptions.
 * Use `create(VersionOptionsSchema)` to create a new message.
 */
export const VersionOptionsSchema: GenMessage<VersionOptions> = /*@__PURE__*/
  messageDesc(file_orm_options, 4);

/**
 * ErasedOptions marks the field that says whether a row is still there.
 *
 * It is a time, and it is null for as long as the row is present. Erasing
 * stamps it rather than deleting the row, and every read leaves out the rows
 * that carry one -- so what pointed at the row goes on pointing at something,
 * which is what a delete takes away: an audit trail that names a row nothing
 * answers to any more, a foreign key that has to be cascaded or refused.
 *
 * It is not a field a caller writes. It does not appear in a PatchRequest, for
 * the same reason the key does not: a row is erased by asking to erase it, not
 * by assigning a date to it. The server stamps it, so it must not be immutable
 * either, and it cannot be the key, the version field, or unique.
 *
 * It is implicitly nullable, since being null is how it says the row is there.
 * Saying `nullable: false` beside it is refused rather than quietly ignored.
 *
 * @generated from message orm.ErasedOptions
 */
export type ErasedOptions = Message<"orm.ErasedOptions"> & {
};

/**
 * Describes the message orm.ErasedOptions.
 * Use `create(ErasedOptionsSchema)` to create a new message.
 */
export const ErasedOptionsSchema: GenMessage<ErasedOptions> = /*@__PURE__*/
  messageDesc(file_orm_options, 5);

