// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file orm/order.proto (package orm, edition 2023)
// option features.field_presence = IMPLICIT;
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Ref } from "./ref_pb";
import { file_orm_ref } from "./ref_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orm/order.proto.
 */
export const file_orm_order: GenFile = /*@__PURE__*/
  fileDesc("Cg9vcm0vb3JkZXIucHJvdG8SA29ybSI+CglPcmRlckl0ZW0SFgoEcmVmcxgBIAMoCzIILm9ybS5SZWYSGQoFb3JkZXIYAiABKA4yCi5vcm0uT3JkZXIqrwEKBU9yZGVyEhUKEU9SREVSX1VOU1BFQ0lGSUVEEAASEwoPT1JERVJfQVNDRU5ESU5HEAESEAoMT1JERVJfQVNDRU5EEAESDQoJT1JERVJfQVNDEAESDQoJT1JERVJfSU5DEAESFAoQT1JERVJfREVTQ0VORElORxACEhEKDU9SREVSX0RFU0NFTkQQAhIOCgpPUkRFUl9ERVNDEAISDQoJT1JERVJfREVDEAIaAhABQjFaKmdpdGh1Yi5jb20vcHJvdG9idWYtb3JtL3Byb3RvYnVmLW9ybS9vcm1wYpIDAggCYghlZGl0aW9uc3DoBw", [file_orm_ref]);

/**
 * @generated from message orm.OrderItem
 */
export type OrderItem = Message<"orm.OrderItem"> & {
  /**
   * @generated from field: repeated orm.Ref refs = 1;
   */
  refs: Ref[];

  /**
   * @generated from field: orm.Order order = 2;
   */
  order: Order;
};

/**
 * Describes the message orm.OrderItem.
 * Use `create(OrderItemSchema)` to create a new message.
 */
export const OrderItemSchema: GenMessage<OrderItem> = /*@__PURE__*/
  messageDesc(file_orm_order, 0);

/**
 * @generated from enum orm.Order
 */
export enum Order {
  /**
   * @generated from enum value: ORDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ORDER_ASCENDING = 1;
   */
  ASCENDING = 1,

  /**
   * @generated from enum value: ORDER_ASCEND = 1;
   */
  ASCEND = 1,

  /**
   * @generated from enum value: ORDER_ASC = 1;
   */
  ASC = 1,

  /**
   * @generated from enum value: ORDER_INC = 1;
   */
  INC = 1,

  /**
   * @generated from enum value: ORDER_DESCENDING = 2;
   */
  DESCENDING = 2,

  /**
   * @generated from enum value: ORDER_DESCEND = 2;
   */
  DESCEND = 2,

  /**
   * @generated from enum value: ORDER_DESC = 2;
   */
  DESC = 2,

  /**
   * @generated from enum value: ORDER_DEC = 2;
   */
  DEC = 2,
}

/**
 * Describes the enum orm.Order.
 */
export const OrderSchema: GenEnum<Order> = /*@__PURE__*/
  enumDesc(file_orm_order, 0);

