// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file orm/patch_op.proto (package orm, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file orm/patch_op.proto.
 */
export const file_orm_patch_op: GenFile = /*@__PURE__*/
  fileDesc("ChJvcm0vcGF0Y2hfb3AucHJvdG8SA29ybSpdCgdQYXRjaE9wEhgKFFBBVENIX09QX1VOU1BFQ0lGSUVEEAASEAoMUEFUQ0hfT1BfQUREEAESEgoOUEFUQ0hfT1BfRVJBU0UQAhISCg5QQVRDSF9PUF9DTEVBUhADQixaKmdpdGh1Yi5jb20vcHJvdG9idWYtb3JtL3Byb3RvYnVmLW9ybS9vcm1wYmIIZWRpdGlvbnNw6Ac");

/**
 * @generated from enum orm.PatchOp
 */
export enum PatchOp {
  /**
   * @generated from enum value: PATCH_OP_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PATCH_OP_ADD = 1;
   */
  ADD = 1,

  /**
   * @generated from enum value: PATCH_OP_ERASE = 2;
   */
  ERASE = 2,

  /**
   * @generated from enum value: PATCH_OP_CLEAR = 3;
   */
  CLEAR = 3,
}

/**
 * Describes the enum orm.PatchOp.
 */
export const PatchOpSchema: GenEnum<PatchOp> = /*@__PURE__*/
  enumDesc(file_orm_patch_op, 0);

