// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file orm/rpc.proto (package orm, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Ref } from "./ref_pb";
import { file_orm_ref } from "./ref_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orm/rpc.proto.
 */
export const file_orm_rpc: GenFile = /*@__PURE__*/
  fileDesc("Cg1vcm0vcnBjLnByb3RvEgNvcm0iGgoGUnBjQWRkEhAKCGRpc2FibGVkGAEgASgIIhoKBlJwY0dldBIQCghkaXNhYmxlZBgBIAEoCCIcCghScGNQYXRjaBIQCghkaXNhYmxlZBgBIAEoCCIcCghScGNFcmFzZRIQCghkaXNhYmxlZBgBIAEoCCJCCgdScGNMaXN0EhAKCGRpc2FibGVkGAEgASgIEhkKB2ZpbHRlcnMYAiADKAsyCC5vcm0uUmVmSgQIAxAESgQIBBAFQixaKmdpdGh1Yi5jb20vcHJvdG9idWYtb3JtL3Byb3RvYnVmLW9ybS9vcm1wYmIIZWRpdGlvbnNw6Ac", [file_orm_ref]);

/**
 * @generated from message orm.RpcAdd
 */
export type RpcAdd = Message<"orm.RpcAdd"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;
};

/**
 * Describes the message orm.RpcAdd.
 * Use `create(RpcAddSchema)` to create a new message.
 */
export const RpcAddSchema: GenMessage<RpcAdd> = /*@__PURE__*/
  messageDesc(file_orm_rpc, 0);

/**
 * @generated from message orm.RpcGet
 */
export type RpcGet = Message<"orm.RpcGet"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;
};

/**
 * Describes the message orm.RpcGet.
 * Use `create(RpcGetSchema)` to create a new message.
 */
export const RpcGetSchema: GenMessage<RpcGet> = /*@__PURE__*/
  messageDesc(file_orm_rpc, 1);

/**
 * @generated from message orm.RpcPatch
 */
export type RpcPatch = Message<"orm.RpcPatch"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;
};

/**
 * Describes the message orm.RpcPatch.
 * Use `create(RpcPatchSchema)` to create a new message.
 */
export const RpcPatchSchema: GenMessage<RpcPatch> = /*@__PURE__*/
  messageDesc(file_orm_rpc, 2);

/**
 * @generated from message orm.RpcErase
 */
export type RpcErase = Message<"orm.RpcErase"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;
};

/**
 * Describes the message orm.RpcErase.
 * Use `create(RpcEraseSchema)` to create a new message.
 */
export const RpcEraseSchema: GenMessage<RpcErase> = /*@__PURE__*/
  messageDesc(file_orm_rpc, 3);

/**
 * RpcList declares the list operation: read the rows the filters match.
 *
 * It is calque's addition -- upstream stops at erase. This tree is calque's
 * published superset of the upstream vocabulary: upstream's numbering is
 * frozen as a subset (a drift test holds it), and a schema that says `list`
 * imports this tree instead of upstream's. `crud` does not enable it: which
 * entities are listable is an API decision a schema states one at a time.
 *
 * @generated from message orm.RpcList
 */
export type RpcList = Message<"orm.RpcList"> & {
  /**
   * @generated from field: bool disabled = 1;
   */
  disabled: boolean;

  /**
   * The edges exposed as filter arms beyond the always-present ref, each
   * named by both name and number -- the same contract Index.refs holds, so a
   * rename breaks the declaration loudly. Explicit rather than "every edge":
   * which relations a listing narrows by is part of the API.
   *
   * @generated from field: repeated orm.Ref filters = 2;
   */
  filters: Ref[];
};

/**
 * Describes the message orm.RpcList.
 * Use `create(RpcListSchema)` to create a new message.
 */
export const RpcListSchema: GenMessage<RpcList> = /*@__PURE__*/
  messageDesc(file_orm_rpc, 4);

